config/routes.rb
Test1::Application.routes.draw do
  devise_for :users
  resources :infos

  root :to => 'home#index'

  get '' => "home#index", as: "home"

end

app/models/daili_ip.rb
class DailiIp < ActiveRecord::Base
  validates_presence_of :name, :port

  def self.random
    self.all[rand(self.count)]
  end

end

app/models/info.rb
class Info < ActiveRecord::Base
  extend FriendlyId
  after_save :setup_slug

  friendly_id :slug

  protected

  def setup_slug
    self.update_column(:slug, "#{self.id} - #{self.name}")
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  def self.zhuaqu
    url = "http://www.youdaili.cn/Daili/http/list_"
    agent = Mechanize.new
    10.times.each do |i|
      page = agent.get url+(i+1).to_s+".html"
      page.search(".newslist_line li a").each do |doc|
        proxy_url = doc.attributes["href"].value
        proxy_page = agent.get proxy_url
        ips = proxy_page.body.encode.scan(/[\d|\.\:]*(?=@)/).flatten.select{|str| str.present?}
        ips.each do |ip|
          if check_ip?(ip)
            puts "#{ip} 有效"
          else
            puts "#{ip} 无效"
          end
        end
      end
    end

  end

  def self.check_ip?(ip)
    agent = Mechanize.new
    ip, port = ip.split(":")
    agent.set_proxy(ip, port)
    is_available = false
    begin
      page = agent.get "http://www.baidu.com"
      is_available = true
      DailiIp.find_or_create_by(name: ip, port: port)
    rescue
    end
    is_available
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_filter :authenticate_user!
  protect_from_forgery with: :exception
  layout "application"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/infos_controller.rb
class InfosController < ApplicationController
  before_action :set_info, only: [:show, :edit, :update, :destroy]

  # GET /infos
  # GET /infos.json
  def index
    @infos = Info.all
  end

  # GET /infos/1
  # GET /infos/1.json
  def show
  end

  # GET /infos/new
  def new
    @info = Info.new
  end

  # GET /infos/1/edit
  def edit
  end

  # POST /infos
  # POST /infos.json
  def create
    @info = Info.new(info_params)
    respond_to do |format|
      if @info.save
        format.html { redirect_to @info, notice: 'Info was successfully created.' }
        format.json { render action: 'show', status: :created, location: @info }
      else
        format.html { render action: 'new' }
        format.json { render json: @info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /infos/1
  # PATCH/PUT /infos/1.json
  def update
    respond_to do |format|
      if @info.update(info_params)
        format.html { redirect_to @info, notice: 'Info was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /infos/1
  # DELETE /infos/1.json
  def destroy
    @info.destroy
    respond_to do |format|
      format.html { redirect_to infos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_info
      @info = Info.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def info_params
      params.require(:info).permit(:name, :age, :desc, :tags)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/views/home/index.html.erb
<span class="row">
  <span class="col-md-8">

<% if nil %>
  <% 3.times do %>
  <span class="col-md-8">
    <div class="text-center"><%= time_ago_in_words(Date.current) %></div>
    <div class="alert alert-success">
      警告框没有默认类，只有基类和修饰类。默认的灰色警告框并没有多少意义。所以您要使用一种内容类。从成功，消息，警告或危险中任选其一
    </div>
  </span>
  <% end %>

  <% 3.times do %>
  <span class="col-md-8 col-md-offset-4 text-right">
    <div class="text-center"><%= time_ago_in_words(Date.current) %></div>
    <div class="alert alert-info">
      可以快速提供在任何警告框中相符的颜色
    </div>
  </span>
  <% end %>
  </span>
<% end %>

  <span class="col-md-8">1111111111</span>

  <span class="col-md-4">
    <h3 class="text-center"><a href="javascript:void(0);">1111111111</a></h3>
    <span class="row">
      <span class="col-md-6"><strong>姓名:</strong> 孙悟空</span>
      <span class="col-md-6"><strong>姓名:</strong> 孙悟空</span>
    </span>
    <span class="row">
      <span class="col-md-6"><strong>姓名:</strong> 孙悟空</span>
      <span class="col-md-6"><strong>姓名:</strong> 孙悟空</span>
    </span>
    <span class="row">
      <a href="javascript:void(0);">西游记西游记西游记西游记西游记西游记游记</a>
      <a href="javascript:void(0);">西游记西游记西游记西游记西游记西游记游记</a>
      <a href="javascript:void(0);">西游记西游记西游记西游记西游记西游记游记</a>
      <a href="javascript:void(0);">西游记西游记西游记西游记西游记西游记游记</a>
    </span>
    <span class="row">
      <h4>我的我的</h4>
    </span>
  </span>

</span>

app/views/infos/_form.html.erb
<%= form_for(@info) do |f| %>
  <% if @info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@info.errors.count, "error") %> prohibited this info from being saved:</h2>

      <ul>
      <% @info.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, placeholder: "名称" %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_area :desc %>
  </div>
  <div class="field">
    <%= f.label :tags %><br>
    <%= f.collection_check_boxes :tags, %w[a b c d], :to_s, :to_s %>
  </div>
  <div class="field">
    <%= f.label :published_at %><br>
    <%= f.text_field :published_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/infos/index.html.erb
<%= asset_url('shijianyoujian_01.jpg') %>
<%= asset_path('shijianyoujian_01.jpg') %>

<h1>Listing infos</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Desc</th>
      <th>Tags</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @infos.each do |info| %>
      <tr>
        <td><%= info.name %></td>
        <td><%= info.age %></td>
        <td><%= info.desc %></td>
        <td><%= info.tags %></td>
        <td><%= link_to 'Show', info %></td>
        <td><%= link_to 'Edit', edit_info_path(info) %></td>
        <td><%= link_to 'Destroy', info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Info', new_info_path %>

app/views/infos/new.html.erb
<h1>New info</h1>

<%= render 'form' %>

<%= link_to 'Back', infos_path %>

app/views/infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @info.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @info.age %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @info.desc %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @info.tags %>
</p>

<%= link_to 'Edit', edit_info_path(@info) %> |
<%= link_to 'Back', infos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Test1</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>